blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/erykkruk/appboard_website/discussions
    about: Ask questions, share ideas, and discuss AppBoard with the community here.
