import Link from "next/link";
import { notFound } from "next/navigation";

import { ArticleLayout } from "@/components/layout/article-layout";
import { JsonLd } from "@/components/ui";
import { getArticle } from "@/lib/blog";
import { buildFaqSchema } from "@/lib/schema";
import { APP_URL, buildPageMetadata } from "@/lib/seo";

import type { FaqEntry } from "@/lib/schema";
import type { Metadata } from "next";
import type { JSX } from "react";

const SLUG = "app-store-screenshot-sizes";
const article = getArticle(SLUG);

export const metadata: Metadata = buildPageMetadata({
  description:
    "Every App Store and Google Play screenshot size required in 2026, verified against Apple and Google documentation, plus how to generate the full set fast.",
  path: `/blog/${SLUG}`,
  title: "App Store screenshot sizes and dimensions (2026 guide)",
});

const FAQ: FaqEntry[] = [
  {
    answer:
      "Apple accepts three sizes for the 6.9 inch iPhone display: 1260 by 2736, 1290 by 2796, and 1320 by 2868 pixels in portrait. Supplying one 6.9 inch set is enough for every smaller iPhone, because Apple scales your screenshots down through 6.5, 6.3, 6.1, 5.5, 4.7, 4 and 3.5 inch displays automatically.",
    question: "What size should App Store screenshots be in 2026?",
  },
  {
    answer:
      "No. You need one 6.9 inch iPhone set if your app runs on iPhone, and one 13 inch iPad set if it runs on iPad. Every other display size is optional and is generated by Apple scaling the largest set you provided.",
    question: "Do I need a different screenshot for every iPhone size?",
  },
  {
    answer:
      "Google does not publish fixed pixel targets. It publishes a range: each screenshot must be between 320 and 3840 pixels on any side, and the longer side cannot be more than twice the shorter side. Google recommends at least 1080 pixels of resolution with a 16:9 or 9:16 aspect ratio. Anything quoting an exact Google phone or tablet size such as 1200 by 1920 is repeating a number Google never published.",
    question: "What size are Google Play screenshots?",
  },
  {
    answer:
      "You can upload 1 to 10 screenshots per localization on the App Store. Google Play requires a minimum of 2 screenshots across different device types and allows a maximum of 8 per device type, with a minimum of 4 for large screens such as tablets and Chromebooks.",
    question: "How many screenshots can I upload to each store?",
  },
  {
    answer:
      "The most common causes are an alpha channel, which Apple rejects outright, an off-by-a-few-pixels export from a design tool, or an image scaled to a size Apple does not list for that display family. Export at one of Apple's exact listed sizes, flatten the image so it has no transparency, and save as PNG or JPEG.",
    question:
      "Why does App Store Connect say the dimensions of one or more screenshots are wrong?",
  },
  {
    answer:
      "Not identically. Apple requires exact pixel dimensions with no alpha channel, and Google accepts a range with a 2:1 constraint. A 1320 by 2868 Apple export happens to satisfy Google's range, so one design can serve both, but the files themselves still need separate exports because Apple rejects transparency and Google requires a different asset set including a 1024 by 500 feature graphic.",
    question:
      "Can I use the same screenshots for the App Store and Google Play?",
  },
  {
    answer:
      "Yes on both stores. Screenshots are metadata, not part of the binary, so you can replace them without shipping a new build. On the App Store, changes to a live version's screenshots go through review; on Google Play they publish through the store listing update flow.",
    question: "Can I update screenshots without releasing a new app version?",
  },
];

export default function Page(): JSX.Element {
  if (!article) {
    notFound();
  }

  return (
    <ArticleLayout article={article}>
      <JsonLd data={buildFaqSchema(`/blog/${SLUG}`, FAQ)} />
      <p>
        The short answer, if that is all you came for: export one iPhone set at{" "}
        <strong>1320 &times; 2868</strong> and, if your app runs on iPad, one set
        at <strong>2064 &times; 2752</strong>. That covers the App Store. For
        Google Play, export the same designs at{" "}
        <strong>1080 &times; 1920</strong> or larger, staying under 3840 pixels
        on the long side. Everything below is the detail behind those numbers,
        checked against Apple and Google documentation in August 2026.
      </p>
      <p>
        It is worth checking, because most of the size guides currently ranking
        are out of date. Several still present 1290 &times; 2796 as the single
        required iPhone size, one still treats the 6.7 inch display as the
        requirement, and at least one publishes invented per-device pixel targets
        for Google Play that Google has never specified.
      </p>

      <h2>App Store: what Apple actually requires</h2>
      <p>
        Apple requires one screenshot set per device family your app supports,
        and it generates the rest. The rules that apply to every upload:
      </p>
      <ul>
        <li>1 to 10 screenshots per localization</li>
        <li>PNG or JPEG only</li>
        <li>
          <strong>No alpha channel and no transparency</strong>, which is the
          single most common cause of a rejected upload
        </li>
        <li>Exact pixel dimensions from the accepted list, not approximations</li>
      </ul>

      <h3>iPhone sizes</h3>
      <table>
        <thead>
          <tr>
            <th>Display</th>
            <th>Portrait</th>
            <th>Required?</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>6.9&Prime;</td>
            <td>1260 &times; 2736, 1290 &times; 2796, 1320 &times; 2868</td>
            <td>Yes, if the app runs on iPhone</td>
          </tr>
          <tr>
            <td>6.5&Prime;</td>
            <td>1284 &times; 2778, 1242 &times; 2688</td>
            <td>Only if you skip 6.9&Prime;</td>
          </tr>
          <tr>
            <td>6.3&Prime;</td>
            <td>1179 &times; 2556, 1206 &times; 2622</td>
            <td>Optional</td>
          </tr>
          <tr>
            <td>6.1&Prime;</td>
            <td>1170 &times; 2532, 1125 &times; 2436, 1080 &times; 2340</td>
            <td>Optional</td>
          </tr>
          <tr>
            <td>5.5&Prime;</td>
            <td>1242 &times; 2208</td>
            <td>Optional</td>
          </tr>
          <tr>
            <td>4.7&Prime;</td>
            <td>750 &times; 1334</td>
            <td>Optional</td>
          </tr>
        </tbody>
      </table>
      <p>
        Landscape is simply the same numbers reversed. The 6.9 inch family covers
        iPhone Air, iPhone 17 Pro Max, 16 Pro Max, 16 Plus, 15 Pro Max, 15 Plus
        and 14 Pro Max.
      </p>

      <h3>iPad sizes</h3>
      <table>
        <thead>
          <tr>
            <th>Display</th>
            <th>Portrait</th>
            <th>Required?</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>13&Prime;</td>
            <td>2064 &times; 2752, 2048 &times; 2732</td>
            <td>Yes, if the app runs on iPad</td>
          </tr>
          <tr>
            <td>12.9&Prime;</td>
            <td>2048 &times; 2732</td>
            <td>Optional</td>
          </tr>
          <tr>
            <td>11&Prime;</td>
            <td>
              1488 &times; 2266, 1668 &times; 2420, 1668 &times; 2388, 1640
              &times; 2360
            </td>
            <td>Optional</td>
          </tr>
          <tr>
            <td>10.5&Prime;</td>
            <td>1668 &times; 2224</td>
            <td>Optional</td>
          </tr>
        </tbody>
      </table>

      <h3>Everything else Apple ships</h3>
      <table>
        <thead>
          <tr>
            <th>Platform</th>
            <th>Sizes</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Mac</td>
            <td>
              1280 &times; 800, 1440 &times; 900, 2560 &times; 1600, 2880 &times;
              1800
            </td>
          </tr>
          <tr>
            <td>Apple TV</td>
            <td>1920 &times; 1080, 3840 &times; 2160</td>
          </tr>
          <tr>
            <td>Apple Vision Pro</td>
            <td>3840 &times; 2160</td>
          </tr>
          <tr>
            <td>Apple Watch Ultra 3</td>
            <td>422 &times; 514</td>
          </tr>
          <tr>
            <td>Apple Watch Series 11 and 10</td>
            <td>416 &times; 496</td>
          </tr>
          <tr>
            <td>Apple Watch Series 9, 8, 7</td>
            <td>396 &times; 484</td>
          </tr>
          <tr>
            <td>Apple Watch Series 6, 5, 4, SE</td>
            <td>368 &times; 448</td>
          </tr>
        </tbody>
      </table>
      <p>
        Watch has one extra rule that catches people: you must use the{" "}
        <strong>same watch size consistently across every localization</strong>.
        Mixing a 416 &times; 496 English set with a 396 &times; 484 German set
        will fail.
      </p>

      <h3>The scaling cascade nobody publishes</h3>
      <p>
        Everyone writes &ldquo;Apple scales down automatically.&rdquo; Here is the
        actual chain, which is why supplying only the largest set is safe:
      </p>
      <ul>
        <li>
          iPhone: 6.9&Prime; falls back to 6.5&Prime;, then 6.1&Prime;, then
          5.5&Prime;, then 4.7&Prime;, then 4&Prime;, then 3.5&Prime;
        </li>
        <li>
          iPad: 13&Prime; falls back to 12.9&Prime;, 11&Prime;, 10.5&Prime; and
          9.7&Prime;
        </li>
      </ul>
      <p>
        Scaling is not free. A 1320 &times; 2868 design resampled to 750 &times;
        1334 loses fine text. If your captions are small, ship a hand-tuned
        4.7 inch set as well. If your captions are large, the cascade is fine.
      </p>

      <h2>Google Play: ranges, not fixed sizes</h2>
      <p>
        This is where most guides go wrong. Google does not specify a phone
        screenshot resolution. It specifies constraints, and any size satisfying
        them is valid.
      </p>
      <table>
        <thead>
          <tr>
            <th>Asset</th>
            <th>Specification</th>
            <th>Count</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Phone screenshots</td>
            <td>
              320 to 3840 px per side; long side no more than 2&times; the short
              side; PNG or JPEG, no alpha
            </td>
            <td>Min 2 across device types, max 8 per type</td>
          </tr>
          <tr>
            <td>Large screens (tablet, Chromebook)</td>
            <td>1080 to 7680 px; 16:9 landscape or 9:16 portrait</td>
            <td>Minimum 4</td>
          </tr>
          <tr>
            <td>Wear OS</td>
            <td>Min 384 &times; 384, 1:1, no device frames allowed</td>
            <td>Minimum 1</td>
          </tr>
          <tr>
            <td>Android XR</td>
            <td>8:5 ratio, 3840 &times; 2400 recommended, max 8 MB each</td>
            <td>4 to 8</td>
          </tr>
          <tr>
            <td>Feature graphic</td>
            <td>1024 &times; 500, JPEG or 24-bit PNG, no alpha</td>
            <td>Required</td>
          </tr>
          <tr>
            <td>App icon</td>
            <td>512 &times; 512, 32-bit PNG with alpha, max 1024 KB</td>
            <td>Required</td>
          </tr>
        </tbody>
      </table>
      <p>
        Two things to notice. Google publishes{" "}
        <strong>no separate 7 inch and 10 inch tablet pixel targets</strong>; one
        large-screen specification covers both. And the icon is the one Google
        asset that <em>requires</em> an alpha channel, which is the exact
        opposite of the screenshot rule. Getting those two backwards is a common
        upload failure.
      </p>

      <h2>Side by side</h2>
      <table>
        <thead>
          <tr>
            <th>Rule</th>
            <th>App Store</th>
            <th>Google Play</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Sizing model</td>
            <td>Exact pixel values from a fixed list</td>
            <td>Range with a 2:1 constraint</td>
          </tr>
          <tr>
            <td>Screenshot count</td>
            <td>1 to 10 per localization</td>
            <td>2 minimum, 8 maximum per device type</td>
          </tr>
          <tr>
            <td>Transparency</td>
            <td>Never allowed</td>
            <td>Not allowed on screenshots, required on the icon</td>
          </tr>
          <tr>
            <td>Auto-scaling</td>
            <td>Yes, largest set covers smaller devices</td>
            <td>No, upload per device type</td>
          </tr>
          <tr>
            <td>Extra required graphic</td>
            <td>None</td>
            <td>Feature graphic 1024 &times; 500</td>
          </tr>
        </tbody>
      </table>

      <h2>Fixing the errors App Store Connect gives you</h2>
      <p>
        Four messages account for nearly every failed screenshot upload:
      </p>
      <ul>
        <li>
          <strong>
            &ldquo;The dimensions of one or more screenshots are wrong&rdquo;
          </strong>{" "}
          usually means an export that is a pixel or two off. Design tools round
          when a canvas is scaled. Set the artboard to the exact target and
          export at 1&times;.
        </li>
        <li>
          <strong>An alpha channel error</strong> means your PNG has
          transparency. Flatten it against a solid background before export.
        </li>
        <li>
          <strong>A device-family mismatch</strong> means you uploaded a valid
          size into the wrong slot, for example a 6.5 inch export into the 6.9
          inch slot.
        </li>
        <li>
          <strong>An inconsistent watch size</strong> across localizations, as
          described above.
        </li>
      </ul>

      <h2>Generating the full set without a design sprint</h2>
      <p>
        The arithmetic is what makes this painful. Two device families, five
        screenshots each, ten languages is 100 image exports, all at exact
        dimensions, all needing translated captions. Doing that by hand in a
        design tool once is tedious; doing it every release is unsustainable.
      </p>
      <p>
        A screenshot generator solves it by separating the design from the
        export. You build one composition, a background, a device frame, your app
        capture and a headline, then the tool renders it at each store size and
        each language. AppBoard includes a{" "}
        <a href={`${APP_URL}/editor`}>free browser-based screenshot editor</a>{" "}
        that does exactly this: device mockups for iPhone, iPad, Android and
        Watch, gradient and mesh backgrounds, text and shape layers, one-click
        templates, panorama layouts that slice one wide image into consecutive
        store frames, and PNG export at the exact dimensions above. It runs
        entirely on your device, needs no account, and there is nothing to
        install.
      </p>
      <p>
        Whatever tool you use, the checklist is the same. Design at the largest
        size. Keep captions large enough to survive scaling. Flatten before
        export. Keep one source file per language rather than one per language
        per device.
      </p>

      <h2>Per-locale sets are where the work really is</h2>
      <p>
        Screenshot sets are per localization on both stores. If your captions are
        baked into the images, and they almost always are, then every language
        you add multiplies your export count. Upload English captions to a
        Japanese listing and Japanese users see English captions.
      </p>
      <p>
        This is the operational cost people underestimate when they decide to
        launch in twelve markets. We covered how to pick which markets are
        actually worth that cost in{" "}
        <Link href="/blog/app-store-localization">
          our guide to app store localization
        </Link>
        .
      </p>

      <h2>Sizes are the easy half</h2>
      <p>
        Getting the pixels right stops your upload from bouncing. It does not
        make anyone install your app. The order of the frames and the message on
        the first two do that, and most viewers never scroll past frame two, so
        that is where the entire conversion decision happens. We wrote about
        ordering and captioning in{" "}
        <Link href="/blog/app-screenshots-that-convert">
          app screenshots that convert
        </Link>
        , which is the companion piece to this one.
      </p>

      <h2>Frequently asked questions</h2>
      {FAQ.map((entry) => (
        <div key={entry.question}>
          <h3>{entry.question}</h3>
          <p>{entry.answer}</p>
        </div>
      ))}

      <p>
        These specifications change whenever Apple ships a new display size. This
        page was verified in August 2026 against Apple&apos;s App Store Connect
        screenshot specifications and Google Play&apos;s graphic asset
        requirements. If you are checking it much later than that, verify the
        6.9 inch numbers before a release.
      </p>
    </ArticleLayout>
  );
}
